[WIP]グループ作成機能の実装
Kaoru1126/chat-space pull request #11
Opened 2017-06-10 11:23 UTC by Kaoru1126

# WHAT
- グループ作成機能の実装
- メンバー追加も込みで実装

# WHY
ChatSpaceの開発に必要だから

2017-06-10 12:00 UTC, Kaoru1126 commented
自分用のメモ
*マスターにマージして、リモートのブランチ削除したら、ローカルから進化したマスターをリモートからプルしろ！！！！！ローカルでマスターからブランチを切る前に！！！新しいマスターを、リモートからプルしろ！！！しないと大変な事になる！！！*

2017-06-14 02:51 UTC, tatsuya4150 requested changes

2017-06-14 02:51 UTC, tatsuya4150 commented on app/controllers/groups_controller.rb
> +    @group = Group.new(group_params)
binding.pryは消しておきましょう。

2017-06-14 02:51 UTC, tatsuya4150 commented on app/controllers/groups_controller.rb
> +    @group = Group.new
ここに追加で、画面に遷移したときにはすでに@group内にcurrent_userが追加してあるようにしておきましょう。

2017-06-14 03:10 UTC, Kaoru1126 commented on app/controllers/groups_controller.rb
> +    @group = Group.new
修正済みです。

2017-06-14 03:27 UTC, kyohei0423 commented on app/controllers/groups_controller.rb
> +    current_user = @group
この記述は必要でしょうか？

2017-06-14 03:27 UTC, kyohei0423 commented on app/controllers/groups_controller.rb
> +      redirect_to root_path
redirect_to を使用する場合は、フラッシュをredirect_toのオプションに含めることができるので一行で書くことができます。

2017-06-14 03:27 UTC, kyohei0423 commented on app/controllers/groups_controller.rb
> +  def move_to_sign_in
こちらのメソッド何処かで使用していますか？

2017-06-14 03:27 UTC, kyohei0423 commented on app/controllers/messages_controller.rb
> +    @groups = Group.all
ユーザーが所属しているグループのみにしましょう

2017-06-14 03:27 UTC, kyohei0423 commented on app/views/groups/new.html.haml
> +  = form_for(@group) do |f|
丸括弧は不要です

2017-06-14 03:27 UTC, kyohei0423 commented on config/routes.rb
> +    post "/groups/new" => "groups#create"
この記述は必要でしょうか？
resoucesを使用しているのであれば不要だと思います。

2017-06-14 03:39 UTC, Kaoru1126 commented on app/controllers/groups_controller.rb
> +      redirect_to root_path
修正済みです。

2017-06-14 03:53 UTC, Kaoru1126 commented on app/views/groups/new.html.haml
> +  = form_for(@group) do |f|
修正済みです。

2017-06-14 03:55 UTC, Kaoru1126 commented on config/routes.rb
> +    post "/groups/new" => "groups#create"
削除しました。

2017-06-14 04:00 UTC, Kaoru1126 commented on app/controllers/groups_controller.rb
> +  def move_to_sign_in
使ってないので削除します。

2017-06-14 04:09 UTC, Kaoru1126 commented on app/controllers/groups_controller.rb
> +    @group = Group.new(group_params)
修正しました。

2017-06-14 04:28 UTC, Kaoru1126 commented on app/controllers/messages_controller.rb
> +    @groups = Group.all
現状使ってないので、一旦削除しました。

2017-06-14 05:44 UTC, Kaoru1126 commented on app/controllers/groups_controller.rb
> +    current_user = @group
変更しました。

2017-06-14 05:53 UTC, Kaoru1126 commented on app/controllers/groups_controller.rb
> +    @group = Group.new
修正済みじゃないです。

2017-06-14 07:29 UTC, merged